# railway.toml
[build]
dockerfilePath = "infrastructure/docker/Dockerfile.api"

[deploy]
startCommand = "sh -c 'unicorn main:app --port $PORT'"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
