version: '3.8'

services:
  api:
    build:
      context: ../../
      dockerfile: infrastructure/docker/Dockerfile.api
    env_file: ../../.env
    volumes:
      - ../../data:/app/data
      - ../../models:/app/models
      - ../../uploads:/app/uploads
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ../../
      dockerfile: infrastructure/docker/Dockerfile.frontend
    env_file: ../../.env
    ports:
      - "8501:8501"
    depends_on:
      - api

  nginx:
    image: nginx:latest
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../index.html:/usr/share/nginx/html/index.html:ro
    ports:
      - "80:80"
    depends_on:
      - api
      - frontend
